### ISSUE TITLE
Friendly error when WebRTC not working

### ISSUE THREAD

**Issue by topheman** [topheman/webrtc-experiments#7]
Not all browsers have WebRTC, ensure that they have a human error that tells that the WebRTC isn't supported and maybe to use some of the browser like firefox, chrome, safari ...

This might happen on Samsung browser on mobile.

This issue was raised by @warpdesign

**Comment by warpdesign** [comment]
I guess [modernizr](https://github.com/Modernizr/Modernizr/tree/master/feature-detects/webrtc) could be a good starting point for that.

**Comment by topheman** [comment]
Already works - example with tor browser : 
<img width="1200" alt="Capture d’écran 2020-03-10 à 21 20 41" src="https://user-images.githubusercontent.com/985982/76355872-533a1580-6315-11ea-8266-fcf2e9caa16e.png">
